Amabili Aguilón García
Carné: 999012483

```{r}
#VECTORES Y MATRICES

Student_1 <- c(50.4,62.3,92.1,77.6, TRUE)
Student_2 <- c(41.7,87.9,75.3,72.4, FALSE)
Student_3 <- c(30.3,67.8,69.3,71.2, FALSE)
Student_4 <- c(65.4,85.1,92.3,96.8, TRUE)
Student_5 <- c(70.4,88.2,95.2,90.7, TRUE)

students_vector <- c(Student_1,Student_2,Student_3,Student_4,Student_5)

Students_matrix <- matrix(students_vector, ncol = 5, nrow = 5, byrow = TRUE)

```

```{r}
#NOMBRADO DE UNA MATRIZ

name_students <- c("Lily Brown","Davis Moore","Susan Taylor","Mike Jones", "Tom Hill")

name_cousrses_legal_age <- c("TIC", "Accounting", "Psychology", "Ethics", "Legal_age")

colnames(Students_matrix) <- name_cousrses_legal_age
rownames(Students_matrix) <- name_students

```

```{r}
total_grade_student <- c(rowsum(Students_matrix [ ,1:4])
                         
result_students <- cbind(Students_matrix)

#intente con unir estos dos pero me sale error entonces utilizaré esto para continuar con el ejercico result_students <- cbind(students_matrix, total_grade_student)
                        
```



```{r}
#SELECCIONANDO ELEMENTOS DE UNA MATRIZ

result_students[c(1,3,5),c(2,4)]

selected_elements <- result_students[c(1,3,5),c(2,4)]

print(selected_elements)

```

```{r}
#DATA FRAMES
students_projection <- data.frame(result_students)

students_projection

subset(students_projection, X5 == 1 & X2 > 80)
```

```{r}
#FUNCIONES, CONDICIONALES Y BUCLES

students <- function(5,5) {
y <- matrix(1, nrow=4, ncol= 4)
  for(i in 1:4){
    for(j in 1:4){
      y[i,j] = 1/(i+j-1)
    }
  }
}
```

```{r}
#DATA FRAMES Y LAPPLY

index_education <-function(grade){
  resultado <- (1+(grade/100))/2
  print(resultado)
}
students_grades_df <- result_students [1:5,1:4] 
index_education(grade = students_grades_df)
all_students_grade <- index_education(grade = students_grades_df)
index_education <-lapply(all_students_grade, index_education)
```

```{r}
#Math utilities

datos <- (students_grades_df[1,1:4])
arithmetic.mean(datos)
datos2 <- c(students_grades_df[2,1:4])
arithmetic.mean(datos2)
datos3 <- c(students_grades_df[3,1:4])
arithmetic.mean(datos3)
datos4 <- c(students_grades_df[4,1:4])
arithmetic.mean(datos4)
datos5 <- c(students_grades_df[5,1:4])
arithmetic.mean(datos5)

Resultados <-c(datos,datos2,datos3,datos4,datos5)

```




